# [START runtime]
runtime: nodejs
vm: true
manual_scaling:
  instances: 1

# [END runtime]

# Temporary workaround for a Cloud SDK bug.
# Ensures that node_modules directory and any .log files are not uploaded (the
# other entries are the default values for skip_files). This will skip any Unix
# hidden files (such as the .git directory)
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^node_modules$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^(.*/)?.*/node_modules/.*$
 - ^(.*/)?.*\.log$
